PR Number: 595
Title: '[GEN][ZH] Add Windows application manifest to executables'
Merged At: '2025-06-01T08:21:52Z'
Author: valeronm
URL: https://github.com/TheSuperHackers/GeneralsGameCode/pull/595
Labels:
- Enhancement
- Minor
- Build
- Gen
- ZH
